name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_BUILD_VERSION: 1.0.${{ github.run_number }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build Release APK
      working-directory: ./android-app
      run: |
        ./gradlew assembleRelease \
          -PversionCode=${{ github.run_number }} \
          -PversionName=${{ env.ANDROID_BUILD_VERSION }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: david-release
        path: android-app/app/build/outputs/apk/release/*.apk
